### PR TITLE
Add possibility to add route intermediate points. Fixes #18

### LINKED ISSUE #18: Possibility to add middle points to the route
It would be nice to specify not only the start and finish point, but also the points the route should go through. For instance, a week ago I needed to hitchhike from Krakow to Voronezh through Lviv, Kyiv and Kharkiv, and the default route wasn't going through Kharkiv, so I needed to download 3 KML files (Krakow-Kyiv, Kyiv-Kharkiv, Kharkiv-Voronezh) to see all the points.

I think it'd be a cool feature and this is the thing I want to implement, but I want to know your opinion, what do you think @NoryDev ?

### PR DESCRIPTION
**Pull request by serge1peshcoff**
Node: In the current state it's totally not for merging, this is WIP for now.

@NoryDev to implement adding intermediate points, the rewriting of the internal API was required, so I've did it. What I did for now is changed the internal API for the project, and it's quite big changes, just wanted to check if it's okay by you and get your opinion on that. (Everything that was working before should work for now as well (the browser version is working, the tests and Rubocop reports are also fine), this is basically the base for future improvement.)

I didn't add the new features yet and I will add them a little bit later and write about it here.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
Also, my idea is to change the API of this library slightly, so the request to `/trip` would accept the array of points instead of `from` and `to` params. My idea is to implement it so the request would look like that:

```
/trip?places[0][name]=Voronezh,+city,+Russia&places[0][lat]=51.6548797&places[0][lon]=39.212949&places[1][name]=Moscow,+city,+Russia&places[1][lat]=55.7507178places[1][lon]=37.6176606
```

instead of 

```
trip?from=Voronezh,+city,+Russia&from_lat=51.6548797&from_lon=39.212949&to=Moscow,+city,+Russia&to_lat=55.7507178&to_lon=37.6176606
```

That way it would be possible to send arbitrary amount of points to Hitchspots instead of just 2.
What do you think?

**Comment by NoryDev** [comment]
Hi @serge1peshcoff, thanks for the PR, I will have a look at your proposition this weekend, I don't have much time until then.

**Comment by serge1peshcoff** [comment]
@NoryDev another thing I've just realised is the `/trip` API can be done that way:

```
/trip?places[][name]=Krakow&places[][lat]=333&places[][lon]=21&places[][name]=Kyiv&places[][name]=Kharkiv&places[][name]=Voronezh
```

without specifying the indexes, Sinatra understands it perfectly.

**Comment by NoryDev** [comment]
@serge1peshcoff I had a look. That's a good proposition 👍
You can go ahead and implement the interface as well.

I must say that I prefer the first one:

```
/trip?places[0][name]=Voronezh,+city,+Russia&places[0][lat]=51.6548797&places[0][lon]=39.212949&places[1][name]=Moscow,+city,+Russia&places[1][lat]=55.7507178places[1][lon]=37.6176606
```

Because the order is important. So I think it's better if the API reflects that.

**Comment by NoryDev** [comment]
Hey @serge1peshcoff, since I didn't hear from you and still liked your feature idea, I have done this change in #23

**Comment by serge1peshcoff** [comment]
@NoryDev that is really lovely, thanks!
You've wrote that there's no visual changes, I'll try to make another PR on that.
(Sorry for not answering, had really tough time busy with other important stuff and forgot about this one)

**Comment by NoryDev** [comment]
@serge1peshcoff no prob 👍

**Pull request closed without merging**
